name: Profile Metrics

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          # Your profile repo: <username>/<username>
          user: hemanthkori
          repo: hemanthkori/hemanthkori
          template: classic
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Base sections
          base: header, activity, community, repositories, metadata

          # Common plugins (tweak as you like)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_details: percentage

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: mastered

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_from: 200  # last 200 events

          # Looks
          config_timezone: Europe/Dublin
          config_display: large
          config_twemoji: yes
